config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    
    if @post.present?
      @post.destroy
    end
    
    redirect_to posts_path
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
    
    if !@post.present?
      redirect_to posts_path
    end
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    
    if @post.present?
      @post.update(post_params)
    end
    
    redirect_to posts_path
  end
  
  def show
    @post = Post.find_by(id: params[:id])
  end
  
  private
    def post_params
      params.require(:post).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Question</h1>

<%= form_for @post do |f| %>
    Question: <%= f.text_field :title %> <br>
    Answers: <%= f.text_area :body %> <br>
    <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Survey prototype</h1>
<%= link_to "Add Question", new_post_path %>
<ul>
<% @posts.each do |this_post| %>
    <li>
        <strong><%= this_post.title %></strong>
        <p>
            <%= this_post.body %>
        </p><br>
        <%= link_to "Delete", 
            post_path(this_post), 
            method: :delete, 
            data: { confirm: "Are you sure you want to delete?" } %>
        <%= link_to "Edit",
            edit_post_path(this_post) %>
        <%= link_to "Show",
            post_path(this_post) %>
    </li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Question</h1>

<%= form_for @post do |f| %>
    Question: <%= f.text_field :title %> <br>
    Answers: <%= f.text_area :body %> <br>
    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>Question #<%= @post.id%></h1>
<h2><% @post.title %></h2>
<p>
    <%= @post.body %>
</p>